services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    container_name: postgres-monitoring
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: monitoring
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql